version: '3.9'

services:
  backend:
    build: .
    container_name: backendproject
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - ./core:/app
    ports:
      - "8002:8002"
    environment:
      - SECRET_KEY=test
      - DEBUG=True



