# Generated by Django 3.2.25 on 2024-11-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20241116_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
